plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

packageExtensions:
  "mongodb@*":
    dependencies:
      bson-ext: "*"
      kerberos: "*"
      "@mongodb-js/zstd": "*"
      aws4: "*"
      mongodb-core: "*"
      bson: "*"
      node-gyp: "*"
      "mongodb-client-encryption": "*"
    peerDependenciesMeta:
      "@mongodb-js/zstd":
        optional: true
      snappy:
        optional: true
      bson-ext:
        optional: true
      kerberos:
        optional: true
  "@mongodb-js/zstd@*":
    peerDependenciesMeta:
      # "./zstd.win32-x64-msvc.node":
      #   optional: true
      "@mongodb-js/zstd-win32-x64-msvc":
        optional: true
      # "./zstd.darwin-x64.node":
      #   optional: true
      "@mongodb-js/zstd-darwin-x64":
        optional: true
      # "./zstd.darwin-arm64.node":
      #   optional: true
      # "./zstd.linux-x64-gnu.node":
      #   optional: true
      "@mongodb-js/zstd-linux-x64-gnu":
        optional: true
      # "./zstd.linux-arm64-gnu.node":
      #   optional: true
      "@mongodb-js/zstd-linux-arm64-gnu":
        optional: true
      # "./zstd.linux-arm-gnueabihf.node":
      #   optional: true
      "@mongodb-js/zstd-linux-arm-gnueabihf":
  "snappy@*":
    peerDependenciesMeta:
      # "./snappy.android-arm64.node":
      #   optional: true
      "@napi-rs/snappy-android-arm64":
        optional: true
      # "./snappy.android-arm-eabi.node":
      #   optional: true
      "@napi-rs/snappy-android-arm-eabi":
        optional: true
      # "./snappy.win32-x64-msvc.node":
      #   optional: true
      "@napi-rs/snappy-win32-x64-msvc":
        optional: true
      # "./snappy.win32-ia32-msvc.node":
      #   optional: true
      "@napi-rs/snappy-win32-ia32-msvc":
        optional: true
      # "./snappy.win32-arm64-msvc.node":
      #   optional: true
      "@napi-rs/snappy-win32-arm64-msvc":
        optional: true
      # "./snappy.darwin-x64.node":
      #   optional: true
      "@napi-rs/snappy-darwin-x64":
        optional: true
      # "./snappy.darwin-arm64.node":
      #   optional: true
      # "./snappy.freebsd-x64.node":
      #   optional: true
      "@napi-rs/snappy-freebsd-x64":
        optional: true
      # "./snappy.linux-x64-musl.node":
      #   optional: true
      "@napi-rs/snappy-linux-x64-musl":
        optional: true
      # "./snappy.linux-x64-gnu.node":
      #   optional: true
      "@napi-rs/snappy-linux-x64-gnu":
        optional: true
      # "./snappy.linux-arm64-musl.node":
      #   optional: true
      "@napi-rs/snappy-linux-arm64-musl":
        optional: true
      # "./snappy.linux-arm64-gnu.node":
      #   optional: true
      "@napi-rs/snappy-linux-arm64-gnu":
        optional: true
      # "./snappy.linux-arm-gnueabihf.node":
      #   optional: true
      "@napi-rs/snappy-linux-arm-gnueabihf":
        optional: true

yarnPath: .yarn/releases/yarn-3.2.3.cjs
